version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - AIRI
  - attw
  - bumpp
  - crossws
  - eventa
  - guiiai
  - injeca
  - listhen
  - logg
  - moeru
  - taze
  - Triggerable
  - tsdown
  - unbird
  - unplugin
  - webworkers
ignoreWords: []
import: []
